using DotCraft.Abstractions;
using DotCraft.Configuration;

namespace DotCraft.Modules;

/// <summary>
/// Registry for managing DotCraft modules.
/// Modules are registered explicitly via <see cref="RegisterModule"/> at startup,
/// using code generated by <c>DotCraft.Gen</c>.
/// </summary>
public sealed class ModuleRegistry
{
    private readonly List<IDotCraftModule> _modules = [];

    private readonly Dictionary<string, IHostFactory> _hostFactories = new();

    /// <summary>
    /// Gets all registered modules.
    /// </summary>
    public IReadOnlyList<IDotCraftModule> Modules => _modules.AsReadOnly();

    /// <summary>
    /// Registers a module with its optional host factory.
    /// </summary>
    public void RegisterModule(IDotCraftModule module, IHostFactory? hostFactory = null)
    {
        _modules.Add(module);
        if (hostFactory != null)
            _hostFactories[module.Name] = hostFactory;
    }

    /// <summary>
    /// Gets all enabled modules sorted by priority (highest first).
    /// </summary>
    public List<IDotCraftModule> GetEnabledModules(AppConfig config)
    {
        return _modules
            .Where(m => m.IsEnabled(config))
            .OrderByDescending(m => m.Priority)
            .ToList();
    }

    /// <summary>
    /// Selects the primary module (highest priority among enabled modules).
    /// </summary>
    public IDotCraftModule? SelectPrimaryModule(AppConfig config)
    {
        return GetEnabledModules(config).FirstOrDefault();
    }

    /// <summary>
    /// Gets the host factory for a module by name.
    /// </summary>
    public IHostFactory? GetHostFactory(string moduleName)
    {
        return _hostFactories.GetValueOrDefault(moduleName);
    }
}
