namespace DotCraft.CLI.Rendering;

/// <summary>
/// Type of rendering event for agent display
/// </summary>
public enum RenderEventType
{
    /// <summary>
    /// Tool call has started - displays dynamic Status with spinner
    /// </summary>
    ToolCallStarted,
    
    /// <summary>
    /// Tool call has completed - converts Status to static MarkupLine history
    /// </summary>
    ToolCallCompleted,
    
    /// <summary>
    /// Response chunk from AI - displayed in streaming mode
    /// </summary>
    ResponseChunk,
    
    /// <summary>
    /// Thinking/reasoning step reported by agent
    /// </summary>
    ThinkingStep,
    
    /// <summary>
    /// Warning message
    /// </summary>
    Warning,
    
    /// <summary>
    /// Error message
    /// </summary>
    Error,
    
    /// <summary>
    /// Stream/query completed
    /// </summary>
    Complete,
    
    /// <summary>
    /// Approval prompt requested - pause rendering
    /// </summary>
    ApprovalRequired,
    
    /// <summary>
    /// Approval prompt completed - resume rendering
    /// </summary>
    ApprovalCompleted,

    Usage,

    /// <summary>
    /// Debug/diagnostic message — dim grey, buffered during Status spinner sessions
    /// </summary>
    Debug
}

/// <summary>
/// Unified rendering event for agent display
/// </summary>
public class RenderEvent
{
    /// <summary>
    /// Type of this rendering event
    /// </summary>
    public RenderEventType Type { get; init; }
    
    /// <summary>
    /// Optional icon emoji for display (e.g., "🔧", "✨", "💭")
    /// </summary>
    public string? Icon { get; init; }
    
    /// <summary>
    /// Optional title for the event (e.g., "Using tool", "Thinking")
    /// </summary>
    public string? Title { get; init; }
    
    /// <summary>
    /// Main content of the event
    /// </summary>
    public string Content { get; init; } = string.Empty;
    
    /// <summary>
    /// Additional information (e.g., tool parameters, result summary)
    /// </summary>
    public string? AdditionalInfo { get; init; }
    
    /// <summary>
    /// Optional color markup for Spectre.Console (e.g., "yellow", "green", "grey")
    /// </summary>
    public string? Color { get; init; }

    /// <summary>
    /// Human-readable formatted description of the tool call.
    /// Generated by <c>ToolRegistry.FormatToolCall</c> in StreamAdapter.
    /// When present, replaces the raw tool name + JSON args in the display.
    /// </summary>
    public string? FormattedDisplay { get; init; }

    /// <summary>
    /// Create a ToolCallStarted event
    /// </summary>
    public static RenderEvent ToolStarted(string? icon, string? title, string content, string? additionalInfo = null, string? formattedDisplay = null)
    {
        return new RenderEvent
        {
            Type = RenderEventType.ToolCallStarted,
            Icon = icon,
            Title = title,
            Content = content,
            AdditionalInfo = additionalInfo,
            Color = "yellow",
            FormattedDisplay = formattedDisplay
        };
    }

    /// <summary>
    /// Create a ToolCallCompleted event
    /// </summary>
    public static RenderEvent ToolCompleted(string? icon, string? title, string content, string? result = null, string? formattedDisplay = null)
    {
        return new RenderEvent
        {
            Type = RenderEventType.ToolCallCompleted,
            Icon = icon,
            Title = title,
            Content = content,
            AdditionalInfo = result,
            Color = "grey",
            FormattedDisplay = formattedDisplay
        };
    }

    /// <summary>
    /// Create a ResponseChunk event
    /// </summary>
    public static RenderEvent Response(string content)
    {
        return new RenderEvent
        {
            Type = RenderEventType.ResponseChunk,
            Content = content
        };
    }

    /// <summary>
    /// Create a ThinkingStep event
    /// </summary>
    public static RenderEvent Thinking(string? icon, string? title, string content)
    {
        return new RenderEvent
        {
            Type = RenderEventType.ThinkingStep,
            Icon = icon,
            Title = title,
            Content = content,
            Color = "cyan"
        };
    }

    /// <summary>
    /// Create a Warning event
    /// </summary>
    public static RenderEvent Warn(string message)
    {
        return new RenderEvent
        {
            Type = RenderEventType.Warning,
            Content = message,
            Color = "yellow"
        };
    }

    /// <summary>
    /// Create an Error event
    /// </summary>
    public static RenderEvent ErrorEvent(string message)
    {
        return new RenderEvent
        {
            Type = RenderEventType.Error,
            Content = message,
            Color = "red"
        };
    }

    /// <summary>
    /// Create a Complete event
    /// </summary>
    public static RenderEvent Completed(string message)
    {
        return new RenderEvent
        {
            Type = RenderEventType.Complete,
            Content = message,
            Color = "green"
        };
    }

    /// <summary>
    /// Create an ApprovalRequired event
    /// </summary>
    public static RenderEvent ApprovalRequest()
    {
        return new RenderEvent
        {
            Type = RenderEventType.ApprovalRequired
        };
    }

    /// <summary>
    /// Create an ApprovalCompleted event
    /// </summary>
    public static RenderEvent ApprovalComplete()
    {
        return new RenderEvent
        {
            Type = RenderEventType.ApprovalCompleted
        };
    }

    /// <summary>
    /// Create a Debug diagnostic message event
    /// </summary>
    public static RenderEvent DebugMessage(string message) => new()
    {
        Type = RenderEventType.Debug,
        Content = message,
        Color = "grey"
    };

    public static RenderEvent TokenUsage(long inputTokens, long outputTokens, long totalTokens)
    {
        return new RenderEvent
        {
            Type = RenderEventType.Usage,
            Content = $"{inputTokens},{outputTokens},{totalTokens}",
            Color = "grey"
        };
    }
}

